import basketButtonFunc from "./components/BasketButton.js";
import basketCalculateFunc from "./components/BasketCalculate.js";
import { formButtonRowFunc, paymentCardInfoFunc } from "./components/BasketForm.js";
import categoryLargeScreenFunction from "./components/CategoryLargeScreen.js";
import categoryMobileFunction from "./components/CategoryMobile.js";
import { colorRadioButtonFunct, colorSwiperButtonFunc } from "./components/ColorButton.js";
import contactFilialFunc from "./components/ContactFilial.js";
import creditCalculatorFunc from "./components/CreditCalculator.js";
import dateCounterFunc from "./components/DateCounter.js";
import descriptionButtonFunc from "./components/DescriptionButton.js";
import favoriButtonFunct from "./components/FavoriButton.js";
import favoriSectionFunc from "./components/Favorisection.js";
import filterCollapseFunc from "./components/FilterCollapse.js";
import fixHeaderFunc from "./components/FIxedHeader.js";
import mobileFilterButtonFunc from "./components/MobileFIlterButton.js";
import numberCounterFunc from "./components/NumberCounter.js";
import priceRangeInputFunc from "./components/PriceRangeInput.js";
import productAmountFunc from "./components/ProductAmount.js";
import scrollButtonFunc from "./components/ScrollButton.js";
import sectionTitleFunc from "./components/SectionTitle.js";
import toolbarFunc from "./components/Toolbar.js";

scrollButtonFunc();
toolbarFunc();
fixHeaderFunc();
sectionTitleFunc();
dateCounterFunc();
numberCounterFunc();
favoriButtonFunct();
favoriSectionFunc();
mobileFilterButtonFunc();
filterCollapseFunc();
colorSwiperButtonFunc();
colorRadioButtonFunct();
descriptionButtonFunc();
productAmountFunc();
basketCalculateFunc();
basketButtonFunc();
formButtonRowFunc();
paymentCardInfoFunc();
contactFilialFunc();
priceRangeInputFunc();
categoryMobileFunction();
categoryLargeScreenFunction();
creditCalculatorFunc();